import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { ExchangeData } from '../types';

const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;
const CARD_WIDTH_IN = 4;
const CARD_HEIGHT_IN = 6;
const IN_TO_MM = 25.4;

const addPageWatermark = (pdf: jsPDF) => {
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text(
        'Generated by SecretSantaMatch.com',
        A4_WIDTH_MM / 2,
        A4_HEIGHT_MM - 5,
        { align: 'center' }
    );
};

export const generateAllCardsPdf = async (exchangeData: ExchangeData): Promise<void> => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const cardElements = document.querySelectorAll<HTMLDivElement>('.printable-card-container');

    if (cardElements.length === 0) {
        throw new Error("Could not find printable card elements. Ensure they are rendered on the page.");
    }
    
    for (let i = 0; i < cardElements.length; i++) {
        const element = cardElements[i];
        if (i > 0) {
            pdf.addPage();
        }
        
        const canvas = await html2canvas(element, {
            scale: 3, // Higher scale for better quality
            useCORS: true,
            allowTaint: true,
            backgroundColor: null, // Use transparent background
        });
        
        const imgData = canvas.toDataURL('image/png');
        
        const cardWidthMM = CARD_WIDTH_IN * IN_TO_MM;
        const cardHeightMM = CARD_HEIGHT_IN * IN_TO_MM;

        const x = (A4_WIDTH_MM - cardWidthMM) / 2;
        const y = (A4_HEIGHT_MM - cardHeightMM) / 2;

        pdf.addImage(imgData, 'PNG', x, y, cardWidthMM, cardHeightMM);
        addPageWatermark(pdf);
    }
    
    pdf.save('Secret_Santa_Cards.pdf');
};


export const generateMasterListPdf = (exchangeData: ExchangeData): void => {
    const pdf = new jsPDF();
    const matches = exchangeData.matches.map(m => ({
        giver: exchangeData.p.find(p => p.id === m.g)!,
        receiver: exchangeData.p.find(p => p.id === m.r)!,
    }));

    pdf.setFontSize(18);
    pdf.text("Secret Santa Master List", 105, 20, { align: 'center' });
    pdf.setFontSize(12);
    pdf.text(`Event Details: ${exchangeData.eventDetails || 'N/A'}`, 10, 30);

    let yPos = 40;
    matches.forEach((match, index) => {
        if (yPos > 280) {
            pdf.addPage();
            yPos = 20;
        }
        const line = `${index + 1}. ${match.giver.name}  ->  ${match.receiver.name}`;
        pdf.text(line, 10, yPos);
        yPos += 10;
    });

    addPageWatermark(pdf);
    pdf.save('Secret_Santa_Master_List.pdf');
};

export const generatePartyPackPdf = async (exchangeData: ExchangeData): Promise<void> => {
    const pdf = new jsPDF();
    pdf.setFontSize(22);
    pdf.text("Secret Santa Party Pack", 105, 20, { align: 'center' });
    pdf.setFontSize(12);
    pdf.text("Thank you for using SecretSantaMatch.com!", 105, 40, { align: 'center' });
    pdf.text("More fun party pack features coming soon.", 105, 50, { align: 'center' });
    
    addPageWatermark(pdf);
    pdf.save('Secret_Santa_Party_Pack.pdf');
};