
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';
import type { ExchangeData, Participant, WERules, WETheme, WEParticipant } from '../types';

type jsPDFWithAutoTable = jsPDF & {
  autoTable: (options: any) => jsPDF;
};

const addPageWatermark = (pdf: jsPDF) => {
    const pageCount = (pdf.internal as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text(
            `Generated by SecretSantaMatch.com | Page ${i} of ${pageCount}`,
            pdf.internal.pageSize.getWidth() / 2,
            pdf.internal.pageSize.getHeight() - 5,
            { align: 'center' }
        );
    }
};

export const generateAllCardsPdf = async (exchangeData: ExchangeData): Promise<void> => {
    // Create a US Letter (8.5x11 inches) PDF in portrait orientation.
    const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'in',
        format: 'letter'
    });
    const cardElements = document.querySelectorAll<HTMLDivElement>('.printable-card-container');

    if (cardElements.length === 0) {
        throw new Error("Could not find printable card elements. Ensure they are rendered on the page.");
    }
    
    for (let i = 0; i < cardElements.length; i++) {
        const element = cardElements[i];
        if (i > 0) {
            pdf.addPage();
        }
        
        const canvas = await html2canvas(element, {
            scale: 3, // Higher scale for better quality
            useCORS: true,
            allowTaint: true,
            backgroundColor: null, // Use transparent background
        });
        
        const imgData = canvas.toDataURL('image/png');
        
        const PAGE_WIDTH_IN = 8.5;
        const PAGE_HEIGHT_IN = 11;
        const MARGIN = 0.5; // 0.5 inch margin on each side

        const availableWidth = PAGE_WIDTH_IN - (MARGIN * 2);
        const availableHeight = PAGE_HEIGHT_IN - (MARGIN * 2);

        const cardAspectRatio = canvas.width / canvas.height;
        
        let cardWidth, cardHeight;

        // Determine scaling to fit within available space while maintaining aspect ratio
        if ((availableWidth / availableHeight) > cardAspectRatio) {
            // Fit to height
            cardHeight = availableHeight;
            cardWidth = availableHeight * cardAspectRatio;
        } else {
            // Fit to width
            cardWidth = availableWidth;
            cardHeight = availableWidth / cardAspectRatio;
        }
        
        // Center the card image on the page
        const x = (PAGE_WIDTH_IN - cardWidth) / 2;
        const y = (PAGE_HEIGHT_IN - cardHeight) / 2;

        pdf.addImage(imgData, 'PNG', x, y, cardWidth, cardHeight);
    }
    
    pdf.save('Secret_Santa_Cards.pdf');
};


export const generateMasterListPdf = (exchangeData: ExchangeData): void => {
    const pdf = new jsPDF() as jsPDFWithAutoTable;
    const matches = exchangeData.matches.map(m => ({
        giver: exchangeData.p.find(p => p.id === m.g)!,
        receiver: exchangeData.p.find(p => p.id === m.r)!,
    }));

    // Document Header
    pdf.setFontSize(22);
    pdf.setFont('helvetica', 'bold');
    pdf.text("Secret Santa - Master List", pdf.internal.pageSize.getWidth() / 2, 20, { align: 'center' });

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    if (exchangeData.eventDetails) {
        const eventDetailsText = `Event Details: ${exchangeData.eventDetails}`;
        const splitDetails = pdf.splitTextToSize(eventDetailsText, pdf.internal.pageSize.getWidth() - 28);
        pdf.text(splitDetails, 14, 30);
    }
    
    const startY = exchangeData.eventDetails ? pdf.getTextDimensions(exchangeData.eventDetails).h + 35 : 30;

    const head = [['Giver', 'Receiver', 'Budget', "Receiver's Wishlist & Details"]];
    
    const body = matches.map(match => {
        const { giver, receiver } = match;
        
        const formatReceiverDetails = (rec: Participant): string => {
            const details = [];
            if (rec.interests?.trim()) details.push(`Interests: ${rec.interests}`);
            if (rec.likes?.trim()) details.push(`Likes: ${rec.likes}`);
            if (rec.dislikes?.trim()) details.push(`Dislikes: ${rec.dislikes}`);
            
            const validLinks = rec.links?.filter(link => link?.trim()).join('\n');
            if (validLinks) {
                details.push(`Links:\n${validLinks}`);
            }
    
            return details.length > 0 ? details.join('\n') : 'No details provided.';
        };

        return [
            giver.name,
            receiver.name,
            receiver.budget || 'N/A',
            formatReceiverDetails(receiver)
        ];
    });

    pdf.autoTable({
        startY,
        head,
        body,
        theme: 'grid',
        headStyles: {
            fillColor: '#c62828', // Primary red
            textColor: 255,
            fontStyle: 'bold',
        },
        columnStyles: {
            0: { cellWidth: 40 },
            1: { cellWidth: 40 },
            2: { cellWidth: 25 },
            3: { cellWidth: 'auto' },
        },
        didDrawPage: (data: any) => {
            // Footer is added at the end by addPageWatermark
        }
    });

    addPageWatermark(pdf);
    pdf.save('Secret_Santa_Master_List.pdf');
};

// --- NEW WHITE ELEPHANT FUNCTIONS ---

export const generateWETurnNumbersPdf = (count: number): void => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const PAGE_WIDTH = pdf.internal.pageSize.getWidth();
    const PAGE_HEIGHT = pdf.internal.pageSize.getHeight();
    const MARGIN = 15;
    const cardWidth = (PAGE_WIDTH - MARGIN * 3) / 2; // 2 cards per row
    const cardHeight = 60;
    const cardsPerPage = 8; // 4 rows x 2 cols

    let x = MARGIN;
    let y = MARGIN;
    let cardsOnPage = 0;

    for (let i = 1; i <= count; i++) {
        if (cardsOnPage >= cardsPerPage) {
            pdf.addPage();
            cardsOnPage = 0;
            y = MARGIN;
            x = MARGIN;
        }

        // Draw Card Border
        pdf.setDrawColor(200);
        pdf.setLineWidth(0.5);
        pdf.rect(x, y, cardWidth, cardHeight);
        
        // Decorative Header
        pdf.setFillColor(240, 249, 255); // Light blue
        pdf.rect(x, y, cardWidth, 15, 'F');
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(10);
        pdf.setTextColor(50, 50, 50);
        pdf.text("WHITE ELEPHANT", x + cardWidth / 2, y + 10, { align: 'center' });

        // The Number
        pdf.setFont('times', 'bold');
        pdf.setFontSize(60);
        pdf.setTextColor(37, 99, 235); // Blue-600
        pdf.text(String(i), x + cardWidth / 2, y + 45, { align: 'center' });

        // Footer
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text("SecretSantaMatch.com", x + cardWidth / 2, y + cardHeight - 3, { align: 'center' });

        cardsOnPage++;
        if (cardsOnPage % 2 === 0) {
            x = MARGIN;
            y += cardHeight + 10;
        } else {
            x += cardWidth + MARGIN;
        }
    }

    pdf.save('White_Elephant_Turn_Numbers.pdf');
};

export const generateWERulesPdf = (rules: WERules, theme: WETheme, groupName?: string, eventDetails?: string): void => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const PAGE_WIDTH = pdf.internal.pageSize.getWidth();
    const PAGE_HEIGHT = pdf.internal.pageSize.getHeight();
    const MARGIN = 20;
    const PRIMARY_RED = '#c62828';
    const PRIMARY_GREEN = '#166534';
    const BORDER_GOLD = '#D4AF37';

    // Draw Decorative Border
    pdf.setDrawColor(PRIMARY_RED);
    pdf.setLineWidth(1.5);
    pdf.rect(MARGIN - 5, MARGIN - 5, PAGE_WIDTH - (MARGIN * 2) + 10, PAGE_HEIGHT - (MARGIN * 2) + 10);
    pdf.setDrawColor(BORDER_GOLD);
    pdf.setLineWidth(0.5);
    pdf.rect(MARGIN - 2, MARGIN - 2, PAGE_WIDTH - (MARGIN * 2) + 4, PAGE_HEIGHT - (MARGIN * 2) + 4);
    
    // Header Title
    pdf.setFont('times', 'bold');
    pdf.setFontSize(32);
    pdf.setTextColor(PRIMARY_RED);
    pdf.text("White Elephant Rules", PAGE_WIDTH / 2, MARGIN + 15, { align: 'center' });
    
    let currentY = MARGIN + 35;

    // Custom Event Header Box
    if (groupName || eventDetails) {
        pdf.setDrawColor(PRIMARY_GREEN);
        pdf.setLineWidth(0.5);
        pdf.setFillColor(240, 253, 244); // Very light green
        pdf.roundedRect(MARGIN, currentY, PAGE_WIDTH - MARGIN * 2, 25, 3, 3, 'FD');
        
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(14);
        pdf.setTextColor(PRIMARY_GREEN);
        if (groupName) pdf.text(groupName, PAGE_WIDTH / 2, currentY + 10, { align: 'center' });
        
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(11);
        pdf.setTextColor(60);
        if (eventDetails) pdf.text(eventDetails, PAGE_WIDTH / 2, currentY + 18, { align: 'center' });
        
        currentY += 35;
    }

    // Game Config Grid
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(50);
    
    const drawConfigItem = (label: string, value: string, x: number, y: number) => {
        pdf.setFillColor(248, 250, 252);
        pdf.setDrawColor(200);
        pdf.rect(x, y, (PAGE_WIDTH - MARGIN * 2) / 3 - 2, 20, 'FD');
        pdf.setFontSize(9);
        pdf.setTextColor(100);
        pdf.text(label, x + 5, y + 6);
        pdf.setFontSize(11);
        pdf.setTextColor(0);
        pdf.setFont('helvetica', 'bold');
        pdf.text(value, x + 5, y + 15);
    };

    const colWidth = (PAGE_WIDTH - MARGIN * 2) / 3;
    drawConfigItem("THEME", theme === 'classic' ? 'Classic' : theme === 'funny' ? 'Funny & Weird' : theme === 'useful' ? 'Useful' : 'Regift', MARGIN, currentY);
    drawConfigItem("STEAL LIMIT", rules.stealLimit === 0 ? 'Unlimited' : `${rules.stealLimit} per gift`, MARGIN + colWidth, currentY);
    drawConfigItem("STEAL BACK", rules.noStealBack ? 'No Immediate' : 'Allowed', MARGIN + colWidth * 2, currentY);

    currentY += 35;

    // Standard Rules List
    const standardRules = [
        { title: "1. Wrap It Up", text: "Everyone brings a wrapped gift to the circle." },
        { title: "2. Draw Numbers", text: "Everyone draws a number to decide the order." },
        { title: "3. First Player", text: "Player #1 picks a gift from the pile and opens it for everyone to see." },
        { title: "4. Next Players", text: "The next player can choose to:\n   a) Pick a new wrapped gift from the pile.\n   b) Steal an already opened gift from another player." },
        { title: "5. Get Stolen From?", text: "If your gift is stolen, you can pick a new gift or steal from someone else (but you can't steal back immediately if that rule is on!)." },
        { title: "6. Game Over", text: "The game ends when the last gift is opened." },
        { title: "7. The Final Twist", text: "Player #1 gets the final turn to swap their gift with anyone else!" }
    ];

    pdf.setFont('times', 'bold');
    pdf.setFontSize(18);
    pdf.setTextColor(PRIMARY_RED);
    pdf.text("How to Play:", MARGIN, currentY);
    
    // Decorative Line
    pdf.setDrawColor(BORDER_GOLD);
    pdf.setLineWidth(0.5);
    pdf.line(MARGIN, currentY + 2, MARGIN + 40, currentY + 2);
    
    currentY += 15;

    standardRules.forEach(rule => {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(11);
        pdf.setTextColor(0);
        pdf.text(rule.title, MARGIN, currentY);
        
        const textHeight = pdf.getTextDimensions(rule.title).h;
        
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(10);
        pdf.setTextColor(60);
        
        const splitText = pdf.splitTextToSize(rule.text, PAGE_WIDTH - MARGIN * 2 - 5);
        pdf.text(splitText, MARGIN, currentY + 5);
        
        currentY += (splitText.length * 5) + 10; // Spacing between rules
    });

    // Footer
    pdf.setFontSize(9);
    pdf.setTextColor(150);
    pdf.text("Generated by SecretSantaMatch.com", PAGE_WIDTH / 2, PAGE_HEIGHT - MARGIN + 2, { align: 'center' });

    pdf.save('White_Elephant_Rules.pdf');
};

export const generateWEGameLogPdf = (history: string[], participants: WEParticipant[], giftState: Record<string, string>, groupName?: string, eventDetails?: string): void => {
    const pdf = new jsPDF() as jsPDFWithAutoTable;
    
    // Header
    pdf.setFontSize(22);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(37, 99, 235); // Blue
    pdf.text("White Elephant Game Summary", pdf.internal.pageSize.getWidth() / 2, 20, { align: 'center' });
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(0);
    if (groupName) pdf.text(groupName, pdf.internal.pageSize.getWidth() / 2, 30, { align: 'center' });
    if (eventDetails) pdf.text(eventDetails, pdf.internal.pageSize.getWidth() / 2, 36, { align: 'center' });

    // Action Log Table
    const body = history.map((entry, index) => [index + 1, entry]);

    pdf.autoTable({
        startY: 45,
        head: [['#', 'Action Log']],
        body: body,
        theme: 'striped',
        headStyles: { fillColor: '#2563eb' },
        columnStyles: { 0: { cellWidth: 15 } }
    });

    // Final Gift Distribution Table
    const giftBody = participants
        .filter(p => giftState && giftState[p.id])
        .map(p => [p.name, giftState[p.id]]);

    if (giftBody.length > 0) {
        // Determine if we need a new page or can fit it
        const finalY = (pdf as any).lastAutoTable.finalY;
        const pageHeight = pdf.internal.pageSize.getHeight();
        
        if (finalY + 60 > pageHeight) {
            pdf.addPage();
            (pdf as any).lastAutoTable.finalY = 20; // Reset Y for new page
        }

        pdf.setFontSize(16);
        pdf.setTextColor(22, 101, 52); // Green
        pdf.text("Final Gift Distribution", pdf.internal.pageSize.getWidth() / 2, (pdf as any).lastAutoTable.finalY + 20, { align: 'center' });

        pdf.autoTable({
            startY: (pdf as any).lastAutoTable.finalY + 25,
            head: [['Player', 'Gift']],
            body: giftBody,
            theme: 'striped',
            headStyles: { fillColor: '#166534' }, // Green for gifts
            columnStyles: { 0: { cellWidth: 60 } }
        });
    }

    addPageWatermark(pdf);
    pdf.save('White_Elephant_Game_Log.pdf');
};

export const generatePartyPackPdf = async (): Promise<void> => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const PAGE_WIDTH = pdf.internal.pageSize.getWidth();
    const PAGE_HEIGHT = pdf.internal.pageSize.getHeight();
    const MARGIN = 15;
    
    const PRIMARY_RED = '#c62828';
    const PRIMARY_GREEN = '#166534';
    const GOLD_ACCENT = '#b49b69';

    // Helper to add a consistent footer
    const addFooter = (pageNumber: number, totalPages: number) => {
        // FIX: Pages with full-page borders (Title, Awards) need a higher footer to prevent overlap.
        const isBorderedPage = [1, 7, 8, 9].includes(pageNumber);
        const yPos = isBorderedPage ? PAGE_HEIGHT - 12 : PAGE_HEIGHT - 8;

        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'italic');
        pdf.setTextColor(150);
        pdf.text(`SecretSantaMatch.com Party Pack | Page ${pageNumber} of ${totalPages}`, PAGE_WIDTH / 2, yPos, { align: 'center' });
    };

    // --- PAGE 1: TITLE PAGE ---
    pdf.deletePage(1); // Start with a fresh document
    pdf.addPage();
    pdf.setFillColor(PRIMARY_GREEN);
    pdf.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
    pdf.setDrawColor(GOLD_ACCENT);
    pdf.setLineWidth(1.5);
    pdf.rect(MARGIN / 2, MARGIN / 2, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - MARGIN);
    pdf.setTextColor('#FFFFFF');
    pdf.setFont('times', 'bold');
    pdf.setFontSize(32);
    pdf.text('SecretSantaMatch.com', PAGE_WIDTH / 2, PAGE_HEIGHT / 2 - 20, { align: 'center' });
    pdf.setFontSize(60);
    pdf.text('Party Pack', PAGE_WIDTH / 2, PAGE_HEIGHT / 2 + 10, { align: 'center' });
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(14);
    pdf.text('Fun printables for your gift exchange!', PAGE_WIDTH / 2, PAGE_HEIGHT / 2 + 30, { align: 'center' });

    // --- BINGO CARDS (6 UNIQUE CARDS, 2 PER PAGE) ---
    const bingoPrompts = [
        "Someone gets socks", "A gift is a mug", "Someone says 'I love it!'", "Gift is re-gifted", "Someone gets candy",
        "Gift is handmade", "Wrapping paper is ripped, not torn", "Someone guesses their Santa", "A gift is a book",
        "Someone gets a candle", "A gift is a gift card", "Someone says 'It's perfect!'", "Someone gets alcohol",
        "A gift is an ornament", "A gift is an experience", "Someone is wearing a Santa hat", "A pet is involved in unwrapping",
        "Someone takes a photo of their gift", "A gift is food-related", "Someone says 'Aww!'", "A gift is for the office",
        "Someone asks 'Who had me?'", "A gift is a game", "Someone needs batteries (not included)"
    ];
    const shuffleArray = (arr: string[]) => arr.sort(() => Math.random() - 0.5);

    for (let i = 0; i < 3; i++) {
        pdf.addPage();
        for (let j = 0; j < 2; j++) { // Two cards per page
            const cardX = MARGIN;
            const cardY = MARGIN + j * ((PAGE_HEIGHT - MARGIN * 2) / 2);
            const cardWidth = PAGE_WIDTH - MARGIN * 2;
            const cardHeight = (PAGE_HEIGHT - MARGIN * 2.5) / 2;
            
            pdf.setDrawColor(PRIMARY_RED);
            pdf.setLineWidth(0.5);
            pdf.rect(cardX, cardY, cardWidth, cardHeight);
            pdf.setFont('times', 'bold');
            pdf.setFontSize(24);
            pdf.setTextColor(PRIMARY_RED);
            pdf.text('SECRET SANTA BINGO', cardX + cardWidth / 2, cardY + 12, { align: 'center' });

            const shuffledPrompts = shuffleArray([...bingoPrompts]);
            const gridSize = 5;
            const cellWidth = cardWidth / gridSize;
            const cellHeight = (cardHeight - 20) / gridSize;

            for (let row = 0; row < gridSize; row++) {
                for (let col = 0; col < gridSize; col++) {
                    const x = cardX + col * cellWidth;
                    const y = cardY + 20 + row * cellHeight;
                    pdf.rect(x, y, cellWidth, cellHeight);
                    
                    pdf.setFont('helvetica', 'normal');
                    pdf.setFontSize(8);
                    pdf.setTextColor(0, 0, 0);

                    let text = '';
                    if (row === 2 && col === 2) {
                        text = 'FREE SPACE\n(Gift Exchange Fun!)';
                        pdf.setFont('helvetica', 'bold');
                    } else {
                        text = shuffledPrompts.pop() || '';
                    }
                    const textLines = pdf.splitTextToSize(text, cellWidth - 4);
                    pdf.text(textLines, x + cellWidth / 2, y + cellHeight / 2, { align: 'center', baseline: 'middle' });
                }
            }
        }
    }

    // --- GUESSING GAME PAGE ---
    pdf.addPage();
    pdf.setFont('times', 'bold');
    pdf.setFontSize(28);
    pdf.setTextColor(PRIMARY_RED);
    pdf.text("Who's My Secret Santa?", PAGE_WIDTH / 2, MARGIN + 5, { align: 'center' });
    pdf.setFontSize(12);
    pdf.setTextColor(0,0,0);
    pdf.text("Write down your guess before the big reveal!", PAGE_WIDTH / 2, MARGIN + 12, { align: 'center' });
    
    const cardRows = 3;
    const cardCols = 2;
    const availableHeightGG = PAGE_HEIGHT - (MARGIN * 2) - 20; // Top header + page margins
    const verticalSpacingGG = 10;
    const totalVerticalSpacingGG = (cardRows - 1) * verticalSpacingGG;
    const guessCardWidth = (PAGE_WIDTH - MARGIN * (cardCols + 1)) / cardCols;
    const guessCardHeight = (availableHeightGG - totalVerticalSpacingGG) / cardRows;

    pdf.setLineDashPattern([1, 1], 0);
    for (let row = 0; row < cardRows; row++) {
        for (let col = 0; col < cardCols; col++) {
            const x = MARGIN + col * (guessCardWidth + MARGIN);
            const y = MARGIN + 20 + row * (guessCardHeight + verticalSpacingGG);
            pdf.setDrawColor(180);
            pdf.rect(x, y, guessCardWidth, guessCardHeight);
            
            pdf.setFont('times', 'italic');
            pdf.setFontSize(14);
            pdf.setTextColor(PRIMARY_GREEN);
            pdf.text("My Secret Santa Guess", x + guessCardWidth / 2, y + 10, { align: 'center' });

            pdf.setFont('helvetica', 'normal');
            pdf.setFontSize(11);
            pdf.setTextColor(0,0,0);
            pdf.text("My Name:", x + 5, y + 25);
            pdf.line(x + 25, y + 25, x + guessCardWidth - 5, y + 25);
            pdf.text("I think my Santa is...", x + 5, y + 40);
            pdf.line(x + 45, y + 40, x + guessCardWidth - 5, y + 40);
        }
    }
    pdf.setLineDashPattern([], 0);

    // --- GIFT TAGS PAGE ---
    pdf.addPage();
    pdf.setFont('times', 'bold');
    pdf.setFontSize(28);
    pdf.setTextColor(PRIMARY_GREEN);
    pdf.text("Festive Gift Tags", PAGE_WIDTH / 2, MARGIN + 5, { align: 'center' });
    pdf.setFontSize(12);
    pdf.setTextColor(0,0,0);
    pdf.text("Print on cardstock and cut out for best results.", PAGE_WIDTH / 2, MARGIN + 12, { align: 'center' });

    const tagRows = 4;
    const tagCols = 2;
    const availableHeightGT = PAGE_HEIGHT - (MARGIN * 2) - 20;
    const verticalSpacingGT = 5;
    const totalVerticalSpacingGT = (tagRows - 1) * verticalSpacingGT;
    const tagWidth = (PAGE_WIDTH - MARGIN * (tagCols + 1)) / tagCols;
    const tagHeight = (availableHeightGT - totalVerticalSpacingGT) / tagRows;
    
    const tagDesigns = ["Merry Christmas!", "Happy Holidays!", "A Special Gift For You", "Do Not Open Until Dec 25th!"];
    const tagColors = [
        { bg: [254, 242, 242], text: [190, 18, 60] }, // Red
        { bg: [236, 253, 245], text: [22, 101, 52] },  // Green
        { bg: [239, 246, 255], text: [30, 64, 175] },  // Blue
        { bg: [255, 251, 235], text: [180, 83, 9] }   // Amber
    ];

    for (let row = 0; row < tagRows; row++) {
        for (let col = 0; col < tagCols; col++) {
             const index = row * tagCols + col;
             const colorTheme = tagColors[index % tagColors.length];
             const designText = tagDesigns[index % tagDesigns.length];

             const x = MARGIN + col * (tagWidth + MARGIN);
             const y = MARGIN + 20 + row * (tagHeight + verticalSpacingGT);

             pdf.setDrawColor(200);
             pdf.setFillColor(colorTheme.bg[0], colorTheme.bg[1], colorTheme.bg[2]);
             pdf.roundedRect(x, y, tagWidth, tagHeight, 3, 3, 'FD');
             
             pdf.setFont('times', 'italic');
             pdf.setFontSize(12);
             pdf.setTextColor(colorTheme.text[0], colorTheme.text[1], colorTheme.text[2]);
             pdf.text(designText, x + tagWidth / 2, y + 10, { align: 'center' });
             
             pdf.setFont('helvetica', 'normal');
             pdf.setFontSize(11);
             pdf.setTextColor(0,0,0);
             pdf.text("To:", x + 8, y + 25);
             pdf.line(x + 18, y + 25, x + tagWidth - 8, y + 25);
             pdf.text("From: Your Secret Santa", x + 8, y + 35);
        }
    }
    
    // --- AWARD CERTIFICATES ---
    const awards = [
        { title: "The Funniest Gift", subtitle: "For the gift that brought the most laughter" },
        { title: "The Most Creative Gift", subtitle: "For the most unique and imaginative present" },
        { title: "The Best Wrapping Award", subtitle: "For the gift that was almost too pretty to open" },
    ];

    awards.forEach(award => {
        pdf.addPage();
        pdf.setDrawColor(GOLD_ACCENT);
        pdf.setLineWidth(1.5);
        pdf.rect(MARGIN / 2, MARGIN / 2, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - MARGIN);
        pdf.setDrawColor(PRIMARY_RED);
        pdf.setLineWidth(0.5);
        pdf.rect(MARGIN / 2 + 2, MARGIN / 2 + 2, PAGE_WIDTH - MARGIN - 4, PAGE_HEIGHT - MARGIN - 4);
        
        pdf.setFont('times', 'bold');
        pdf.setFontSize(22);
        pdf.setTextColor(PRIMARY_GREEN);
        pdf.text("Secret Santa Superlative", PAGE_WIDTH / 2, MARGIN + 20, { align: 'center' });

        pdf.setFontSize(40);
        pdf.setTextColor(PRIMARY_RED);
        pdf.text(award.title, PAGE_WIDTH / 2, PAGE_HEIGHT / 2 - 20, { align: 'center' });

        pdf.setFont('times', 'italic');
        pdf.setFontSize(16);
        pdf.setTextColor(0,0,0);
        pdf.text(award.subtitle, PAGE_WIDTH / 2, PAGE_HEIGHT / 2 - 5, { align: 'center' });
        
        pdf.setFont('helvetica', 'normal');
        pdf.text("Awarded to:", PAGE_WIDTH / 2, PAGE_HEIGHT / 2 + 30, { align: 'center' });
        pdf.setDrawColor(0);
        pdf.setLineWidth(0.2);
        pdf.line(MARGIN + 30, PAGE_HEIGHT / 2 + 45, PAGE_WIDTH - MARGIN - 30, PAGE_HEIGHT / 2 + 45);

        const presentedByText = "Presented by:";
        const textWidth = pdf.getTextDimensions(presentedByText).w;
        const startXText = MARGIN + 30;
        const yPos = PAGE_HEIGHT - MARGIN - 25;
        const startXLine = startXText + textWidth + 3; // 3mm gap
        const endXLine = PAGE_WIDTH - MARGIN - 30;

        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(12);
        pdf.setTextColor(0,0,0);
        
        pdf.text(presentedByText, startXText, yPos);
        pdf.setDrawColor(0);
        pdf.setLineWidth(0.2);
        pdf.line(startXLine, yPos, endXLine, yPos);
    });
    
    // Add footers to all pages
    const totalPages = pdf.internal.pages.length - 1;
    for(let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        addFooter(i, totalPages);
    }
    
    pdf.save('Secret_Santa_Party_Pack.pdf');
};
